### ISSUE TITLE
add index.html 

### ISSUE THREAD

**Issue by Neeraaaj** [pranitrathod/hacktoberfest2023#1]
add a html page with hacktober information in it

**Comment by Neeraaaj** [comment]
@pranitrathod shall i start working on this?

**Comment by pranitrathod** [comment]
You can add and please inform me here that your PR got accepted by the team of hacktoberfest!
@Neeraaaj

**Comment by pranitrathod** [comment]
I am planning to make new repo as well, please feel free there to PR ill review it and merge it 
@Neeraaaj

**Comment by Neeraaaj** [comment]
it's your repo you'll be accepting the PR/MR right?

**Comment by pranitrathod** [comment]
It's my repo I'll accept it @pranitrathod 
But I'll be creating new too so you follow those repo too and PR me@Neeraaaj

**Comment by Neeraaaj** [comment]
ohh! okay okay

**Comment by Neeraaaj** [comment]
pls Merge the pull request!

**Comment by Neeraaaj** [comment]
pls Merge the pull req @pranitrathod

**Comment by pranitrathod** [comment]
You from Mumbai Airoli?
@Neeraaaj are you working professionals?
