### ISSUE TITLE
Update CSS. 

### ISSUE THREAD

**Issue by abhaygzb15** [pranitrathod/hacktoberfest2023#3]
@pranitrathod Hey!! Can I work on improving the CSS for this repo under hactoberfest contribution ?

**Comment by pranitrathod** [comment]
Sure! 
@abhaygzb15

**Comment by pranitrathod** [comment]
Make your PR @abhaygzb15 I'll review it

**Comment by pranitrathod** [comment]
@abhaygzb15 I have added you in my github follower, make sure you stay up-to-date with other contribution in the future!

**Comment by pranitrathod** [comment]
@abhaygzb15 FOLLOW

**Comment by pranitrathod** [comment]
Please PR your request code to this repo 
Thank you @abhaygzb15 
https://github.com/pranitrathod/Web

**Comment by pranitrathod** [comment]
Please PR your request code to this repo 
Thank you @abhaygzb15 
https://github.com/pranitrathod/Web
and also remember to give valid PR name
For example: build new nav bar or create new feature
