### ISSUE TITLE
Hello World in c++

### ISSUE THREAD

**Issue by priyamaggarwal18** [pranitrathod/hacktoberfest2023#7]
Hello @pranitrathod, as in your README file it says to code hello world in any language I would request you to assign me in HTML and then please do merge it .

**Comment by pranitrathod** [comment]
Please atleast do in some proper Language @priyamaggarwal18 for example golang or rust or cpp or java

**Comment by priyamaggarwal18** [comment]
okay i will do it in cpp.

**Comment by priyamaggarwal18** [comment]
@pranitrathod do I have to make a new issue ? Or edit this issue

**Comment by pranitrathod** [comment]
Just PR the code no need to edit or send new issue!! @priyamaggarwal18

**Comment by priyamaggarwal18** [comment]
okay

**Comment by priyamaggarwal18** [comment]
see, I have made a PR. also, please add a label for Hacktoberfest and Hacktoberfest accepted

**Comment by pranitrathod** [comment]
You don't have to write/spam the issue section we maintainer do check everything
@priyamaggarwal18 and please understand that "THE TAG" you constantly referring is already been tag on this repo 
Go to my my this repo>About section>tags
there you'll find hacktoberfest , hacktoberfest- accepted we never tag such names on issues rather then bug,doc/ goodIssue 

Thank you!

**Comment by priyamaggarwal18** [comment]
Okay, sorry for misunderstanding.

**Comment by pranitrathod** [comment]
@ahmedrazabaloch read the conversation
